# This is a basic workflow to help you get started with Actions

name: Update Github Stats

on:
  schedule:
    - cron: "47 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install requirements
        run: |
          npm install
          
      - name: Github Configurations
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          
      - name: Update Template
        run: |
          node updater.js ${{ github.repository_owner }} atom
        env:
          GHT: ${{ secrets.METRICS_TOKEN }}
          
      - name: commiting changed svg template
        run: |
          git add .
          git commit -m "Github Stats updated ðŸŽ‰" || echo
          git push
